#!/bin/bash

export QP_ROOT=$(dirname $0)

exec bash --init-file <(cat << EOF

[[ -f \${HOME}/.bashrc ]] && source \${HOME}/.bashrc 

ESC=\$(printf "\\e")

function check_ezfio() {
  if [[ -d \${EZFIO_FILE} ]] ; then
    printf "\\e[0;32m|\${EZFIO_FILE}>\\e[m"
  else
    printf "\\e[0;31m|\${EZFIO_FILE}>\\e[m"
  fi
}

PS1="\${PS1%$ }\\\$(check_ezfio) \$ "
source \${QP_ROOT}/quantum_package.rc
EOF
)


